name: Build Release APK

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties with secrets
        run: |
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" >> local.properties
          echo "APPMETRICA_API_KEY=${{ secrets.APPMETRICA_API_KEY }}" >> local.properties

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}


      - name: Debug outputs
        run: |
          echo "=== Содержимое папки release ==="
          ls -la app/build/outputs/apk/release/ || echo "Папка release не найдена"
          echo "=== Все APK-файлы в проекте ==="
          find . -name "*.apk" || echo "APK-файлы не найдены"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned-signed.apk