name: Deploy To Google Play

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-build:
    name: Verify Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties with secrets
        run: |
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" >> local.properties
          echo "APPMETRICA_API_KEY=${{ secrets.APPMETRICA_API_KEY }}" >> local.properties
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> local.properties

      - name: Verify build
        run: ./gradlew assembleDebug check

#  distribute:
#    name: Distribute bundle to Google Play
#    needs: verify-build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: 17
#          cache: 'gradle'
#
#      - name: Version Bump
#        uses: chkfung/android-version-actions@v1.2.3
#        with:
#          gradlePath: app/build.gradle.kts
#          versionCode: ${{ github.run_number }}
#
#      - name: Assemble Release Bundle
#        run: ./gradlew bundleRelease
#
#      - name: Sign Release
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
#          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
#          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
#          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}
#
#      - name: Setup Authorization with Google Play Store
#        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json
#
#      - name: Deploy bundle to Google Play
#        uses: r0adkll/upload-google-play@v1.1.3
#        with:
#          serviceAccountJson: service_account.json
#          packageName: nl.jovmit.androiddevs
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: 'internal'
#          status: 'draft'